# Generated by Django 5.1.3 on 2024-12-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movie_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='images',
        ),
    ]
