# Generated by Django 5.1.3 on 2024-12-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cartitems_movie_datetime_alter_cartitems_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='seat_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seat'),
        ),
    ]
