# Generated by Django 5.1.3 on 2024-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cartitems_seat_numbers_alter_cartitems_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
